# Generated by Django 3.0.5 on 2021-01-10 19:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('loc', models.TextField(default='m0', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Sname', models.CharField(max_length=220)),
                ('Bname', models.CharField(max_length=220)),
                ('stuid', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Sid', models.CharField(default=None, max_length=225)),
                ('model', models.CharField(default=None, max_length=6)),
                ('mode', models.CharField(default=None, max_length=25)),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name', models.CharField(default='Ques', max_length=60, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.Image')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='dadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.User'),
        ),
        migrations.CreateModel(
            name='Dor',
            fields=[
                ('strart', models.TimeField()),
                ('finish', models.TimeField()),
                ('topic', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('qtion', django.contrib.postgres.fields.hstore.HStoreField()),
                ('toool', models.IntegerField()),
                ('name', models.CharField(default='name', max_length=50, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.User')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.Lesson')),
            ],
        ),
    ]
