# Generated by Django 3.1.7 on 2021-03-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('TYPE', models.CharField(choices=[('دینامیک', 'dynamic'), ('استاتیک', 'static')], default='static', max_length=15, verbose_name='نوع')),
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='نام')),
                ('msgid', models.TextField(default=None)),
                ('bmodsa', models.TextField(default=None)),
                ('F', models.CharField(default=None, max_length=100)),
                ('msg', models.TextField()),
                ('bmods', models.TextField()),
                ('CFormat', models.CharField(choices=[('in', 'ساخت سرور'), ('db', 'از طرف دیتابیس')], default='in', max_length=2, verbose_name='ساخت')),
            ],
            options={
                'verbose_name': 'بازخورد',
                'verbose_name_plural': 'بازخورد ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('loc', models.CharField(default='example: math mosallasat 1 Q1', max_length=120, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('image', models.BinaryField(default=None)),
                ('ftype', models.CharField(max_length=7, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویرها',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='نام درس')),
                ('Ename', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='نام لاتین')),
                ('small_name', models.TextField(default='mth', verbose_name='اسم مخفف')),
                ('topic', models.TextField(default='')),
                ('topics', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
            },
        ),
        migrations.CreateModel(
            name='Massenger',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('sender', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MSG',
            fields=[
                ('body', models.TextField()),
                ('Type', models.CharField(max_length=20)),
                ('keysave', models.TextField(default=None)),
                ('Sid', models.CharField(default=None, max_length=225, verbose_name='id سروش')),
                ('time', models.IntegerField(default=None)),
                ('File', models.TextField(default=None)),
                ('keyb', models.TextField(default='')),
                ('rid', models.TextField(default='0', primary_key=True, serialize=False)),
                ('Format', models.CharField(choices=[('input', 'ورودی'), ('output', 'خروجی')], default='output', max_length=10, verbose_name='نوع')),
                ('CFormat', models.CharField(choices=[('in', 'ساخت سرور'), ('db', 'از طرف دیتابیس'), ('ot', 'سمت کاربر')], default='in', max_length=2, verbose_name='ساخت')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.CharField(default='stu', max_length=8, primary_key=True, serialize=False, verbose_name='نام اصلی')),
                ('Fname', models.TextField(default=' بررسی و شرکت در فراسنج ها', verbose_name='نام فرعی')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='نام مسئولیت')),
                ('Fname', models.CharField(default=None, max_length=150, verbose_name='نام فارسی')),
                ('options', models.CharField(default='e', max_length=1, verbose_name='دسترسی')),
                ('optionsave', models.TextField(default='e')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': ' نقش ها ',
            },
        ),
        migrations.CreateModel(
            name='sekey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ykey', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Sname', models.CharField(default='نام', max_length=220, verbose_name='نام')),
                ('Bname', models.CharField(default='نام', max_length=220, verbose_name='نام خانوادگی')),
                ('stuid', models.CharField(default='None', max_length=18, verbose_name='کد کلاسی')),
                ('Sid', models.TextField(default='', primary_key=True, serialize=False, verbose_name='id سروش')),
                ('node', models.CharField(default='0', max_length=20)),
                ('mode2', models.CharField(default='0', max_length=10)),
                ('lmods', models.TextField(default='', verbose_name='ماد قبلی')),
                ('lmod', models.CharField(default='', max_length=1)),
                ('nmod', models.CharField(default='0', max_length=1)),
                ('nmods', models.TextField(default='')),
                ('lkeyb', models.TextField(default='')),
                ('lkeybs', models.TextField(default=None)),
                ('do', models.BooleanField(default=True)),
                ('sign', models.BooleanField(default=False)),
                ('sign2', models.BooleanField(default=False)),
                ('lastmsg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.msg')),
                ('massenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.massenger')),
                ('mode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.feedback')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.role', verbose_name='نقش')),
                ('signkey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.sekey')),
            ],
            options={
                'verbose_name': 'فرهنگی',
                'verbose_name_plural': 'فرهنگی',
            },
        ),
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.FloatField(default=0)),
                ('etime', models.FloatField(default=0)),
                ('time', models.FloatField(default=0)),
                ('mode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name', models.CharField(default='Ques', max_length=60, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.image')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.lesson')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='dadmin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.user', verbose_name='سرگروه'),
        ),
        migrations.CreateModel(
            name='Dor',
            fields=[
                ('strart', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('topicsave', models.TextField(default=None)),
                ('topic', models.TextField(default='')),
                ('qtion', models.TextField(default='')),
                ('qtionid', models.TextField(default=None)),
                ('toool', models.IntegerField()),
                ('name', models.CharField(default='name', max_length=50, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.user')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.lesson')),
            ],
            options={
                'verbose_name': 'فراسنج',
                'verbose_name_plural': 'فراسنج ها',
            },
        ),
        migrations.CreateModel(
            name='door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Progress', models.IntegerField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.user')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.dor')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'دور ها',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Sid', models.TextField(primary_key=True, serialize=False)),
                ('Self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.user')),
            ],
        ),
    ]
