# Generated by Django 3.0.5 on 2021-01-11 06:39

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('loc', models.TextField(default='m0', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='نام درس')),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='موضوعات')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='نام مسئولیت')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Sname', models.CharField(max_length=220, verbose_name='نام')),
                ('Bname', models.CharField(max_length=220, verbose_name='نام خانوادگی')),
                ('stuid', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='کد کلاسی')),
                ('Sid', models.CharField(default=None, max_length=225, verbose_name='id سروش')),
                ('model', models.CharField(default='0', max_length=6)),
                ('mode', models.CharField(default='0', max_length=25)),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.Role', verbose_name='نقش')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name', models.CharField(default='Ques', max_length=60, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.Image')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='dadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.User', verbose_name='سرگروه'),
        ),
        migrations.CreateModel(
            name='Dor',
            fields=[
                ('strart', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('topic', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('qtion', django.contrib.postgres.fields.hstore.HStoreField()),
                ('toool', models.IntegerField()),
                ('name', models.CharField(default='name', max_length=50, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.User')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Progress', models.IntegerField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.User')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Damasanj.Dor')),
            ],
        ),
    ]
