# Generated by Django 3.0.5 on 2021-01-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dor',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.User'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='dadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Damasanj.User'),
        ),
    ]
