# Generated by Django 3.1.5 on 2021-01-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0002_msg_cformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='CFormat',
            field=models.CharField(choices=[('in', 'ساخت سرور'), ('db', 'از طرف دیتابیس')], default='in', max_length=2, verbose_name='ساخت'),
        ),
        migrations.AddField(
            model_name='user',
            name='lmsgn',
            field=models.TextField(default='None', verbose_name='نام پیام آخر'),
        ),
        migrations.AddField(
            model_name='user',
            name='modn',
            field=models.TextField(default='start0', verbose_name='نام مود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Damasanj.feedback'),
        ),
    ]
