# Generated by Django 3.1.5 on 2021-01-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0003_auto_20210119_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lmsgn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modn',
        ),
    ]
