# Generated by Django 3.1.5 on 2021-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0004_auto_20210119_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='CFormat',
            field=models.CharField(choices=[('in', 'ساخت سرور'), ('db', 'از طرف دیتابیس'), ('ot', 'سمت کاربر')], default='in', max_length=2, verbose_name='ساخت'),
        ),
    ]
