# Generated by Django 3.1.5 on 2021-01-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0006_auto_20210119_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Fname',
            field=models.CharField(default=None, max_length=150, verbose_name='نام فارسی'),
        ),
    ]
