# Generated by Django 3.1.5 on 2021-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0008_auto_20210123_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.CharField(default='stu', max_length=8, primary_key=True, serialize=False, verbose_name='نام اصلی')),
                ('Fname', models.TextField(default=' بررسی و شرکت در فراسنج ها', verbose_name='نام فرعی')),
            ],
        ),
        migrations.RenameField(
            model_name='sekey',
            old_name='xkey',
            new_name='ykey',
        ),
    ]
