# Generated by Django 3.1.5 on 2021-01-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0009_auto_20210124_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spas',
        ),
    ]
