# Generated by Django 3.1.5 on 2021-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0010_remove_user_spas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='TYPE',
            field=models.CharField(choices=[('دینامیک', 'dinamic'), ('استاتیک', 'static')], default='static', max_length=15, verbose_name='نوع'),
        ),
    ]
