# Generated by Django 3.1.5 on 2021-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Damasanj', '0015_user_sign2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='F',
        ),
    ]
